/* Status page — renders public/status.json (generated by scripts/update-status.cjs,
 * refreshed by the weekly prod-watch workflow). Static data, zero network calls. */
import { $ } from '../lib/dom';

interface ToolStatus {
  id: string;
  name: string;
  icon: string;
  href: string;
  prettyUrl: string;
  method: string;
  verifiedAt: string;
  ok: boolean;
}

interface StatusData {
  generatedAt: string;
  allGood: boolean;
  tools: ToolStatus[];
  probes: { name: string; result: string; verifiedAt: string }[];
}

const when = (iso: string): string => {
  const d = new Date(iso);
  return isNaN(d.getTime()) ? iso : d.toISOString().slice(0, 16).replace('T', ' ') + ' UTC';
};

async function main(): Promise<void> {
  const res = await fetch(new URL('status.json', document.baseURI), { cache: 'no-store' });
  const data = (await res.json()) as StatusData;

  const summary = $('#summary');
  summary.innerHTML = data.allGood
    ? `<span class="pill ok">✅ All ${data.tools.length} tools verified</span>
       <p>Last full check: <b>${when(data.generatedAt)}</b> — every route 200, every engine probe passed.</p>`
    : `<span class="pill warn">⚠️ Issues detected</span>
       <p>Last check: <b>${when(data.generatedAt)}</b> — see rows below. Failures block CI, so this page is never silently stale.</p>`;

  const rows = $('#rows');
  for (const t of data.tools) {
    const row = document.createElement('div');
    row.className = 'status-row';
    const mark = t.ok === false ? '⚠️' : '✅';
    row.innerHTML = `
      <span class="sr-icon">${t.icon}</span>
      <a class="sr-name" href="${t.href}">${mark} ${t.name}</a>
      <a class="sr-pretty" href="${t.prettyUrl}">${t.prettyUrl}</a>
      <span class="sr-method">${t.method}</span>
      <span class="sr-when">${when(t.verifiedAt)}</span>`;
    rows.appendChild(row);
  }

  const probeRows = data.probes
    .map((p) => `<div class="status-row probe"><span class="sr-icon">🔬</span><span class="sr-name">${p.name}</span><span class="sr-method">${p.result}</span><span class="sr-when">${when(p.verifiedAt)}</span></div>`)
    .join('');
  rows.insertAdjacentHTML('beforeend', probeRows);
}

void main();
