# Pushes regenerated funnel/<slug>/ content to each tool's standalone repo.
# Runs locally (gh auth) or in CI (GH_TOKEN secret, see .github/workflows/funnel-sync.yml).
# Only pushes when the working tree actually differs from HEAD — no-op otherwise.
import os, subprocess, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FUNNEL = os.path.join(ROOT, 'funnel')
OWNER = 'Kayforkind'

REPO = {
    'photo-privacy-kit': 'NavigatorsLab-Photo-Privacy-Kit',
    'metadata-hidden-data-checker': 'NavigatorsLab-Metadata-Checker',
    'image-shrinker': 'NavigatorsLab-Image-Shrinker',
    'scan-screenshot-cleaner': 'NavigatorsLab-Scan-Cleaner',
    'local-e-sign-pad': 'NavigatorsLab-E-Sign-Pad',
    'receipts-to-pdf': 'NavigatorsLab-Receipts-to-PDF',
    'receipt-ocr-to-csv': 'NavigatorsLab-Receipt-OCR',
    'qr-studio': 'NavigatorsLab-QR-Studio',
    'audio-trimmer': 'NavigatorsLab-Audio-Trimmer',
    'invoice-quote-generator': 'NavigatorsLab-Invoice-Generator',
    'batch-rename-and-sort': 'NavigatorsLab-Batch-Rename',
    'print-shop-prep': 'NavigatorsLab-Print-Shop-Prep',
    'pdf-pages': 'NavigatorsLab-PDF-Pages',
    'text-diff': 'NavigatorsLab-Text-Diff',
    'text-stats': 'NavigatorsLab-Text-Stats',
}

def run(args, cwd=None, check=True):
    r = subprocess.run(args, cwd=cwd, capture_output=True, text=True)
    if check and r.returncode != 0:
        raise RuntimeError(f"{' '.join(args)}\n{r.stdout}\n{r.stderr}")
    return (r.stdout + r.stderr).strip()

def main():
    token = os.environ.get('GH_TOKEN') or os.environ.get('GITHUB_TOKEN') or ''
    if not token:
        print('FUNNEL_TOKEN / GH_TOKEN not configured — skipping push. '
              'Set the FUNNEL_TOKEN repo secret (contents:write + administration:write) '
              'to enable CI sync, or run locally with GH_TOKEN=$(gh auth token).')
        return
    failures = []
    pushed, uptodate = [], []
    summary_path = os.environ.get('GITHUB_STEP_SUMMARY')
    for slug, name in REPO.items():
        d = os.path.join(FUNNEL, slug)
        if not os.path.isdir(os.path.join(d, '.git')):
            print(f'skip (no git repo): {slug}')
            continue
        try:
            run(['git', 'add', '-A'], cwd=d)
            dirty = run(['git', 'status', '--porcelain'], cwd=d)
            if not dirty:
                print(f'up-to-date: {name}')
                uptodate.append(name)
                continue
            run(['git', '-c', 'user.name=NavigatorsLab Funnel Sync',
                 '-c', 'user.email=kazim.r.merchant@users.noreply.github.com',
                 'commit', '-m',
                 'Sync from NavigatorsLab-Tools: refreshed README/redirector metadata\n'
                 '\nRegenerated by scripts/funnel-gen.py from public/tools.json.\n'
                 '\n\U0001F916 Generated with Codebuff'
                 '\nCo-Authored-By: Codebuff <noreply@codebuff.com>'], cwd=d)
            if token:
                run(['git', 'remote', 'set-url', 'origin',
                     f'https://x-access-token:{token}@github.com/{OWNER}/{name}.git'], cwd=d)
            run(['git', 'push', 'origin', 'main'], cwd=d)
            print(f'pushed: {name}')
            pushed.append(name)
        except Exception as e:  # noqa: BLE001 — one bad repo must not stop the rest
            failures.append(name)
            print(f'FAIL: {name}: {e}')
    if failures:
        print('FAILED repos:', ', '.join(failures))
    if summary_path:
        with io.open(summary_path, 'a', encoding='utf-8') as s:
            s.write('## Funnel sync result\n\n')
            s.write(f'- **Pushed ({len(pushed)}):** ' + (', '.join(pushed) or '—') + '\n')
            s.write(f'- **Up-to-date ({len(uptodate)}):** ' + (', '.join(uptodate) or '—') + '\n')
            if failures:
                s.write(f'- **FAILED ({len(failures)}):** ' + ', '.join(failures) + '\n')
    if failures:
        sys.exit(1)
    print('FUNNEL SYNC DONE')

if __name__ == '__main__':
    main()
